package com.yeab.ticketing.common.error;

/**
 * Stable API error codes returned to clients across all services.
 */
public enum ErrorCode {
    VALIDATION_FAILURE,
    RESOURCE_NOT_FOUND,
    METHOD_NOT_ALLOWED,
    UNAUTHORIZED,
    FORBIDDEN,
    SEAT_ALREADY_RESERVED,
    RESERVATION_NOT_FOUND,
    RESERVATION_EXPIRED,
    INVALID_RESERVATION_STATE,
    PAYMENT_FAILED,
    DUPLICATE_PAYMENT,
    INVALID_PAYMENT_STATE,
    WEBHOOK_SIGNATURE_INVALID,
    TICKET_GENERATION_FAILURE,
    RATE_LIMIT_EXCEEDED,
    EVENT_NOT_AVAILABLE,
    SERVICE_UNAVAILABLE,
    CONFLICT,
    INTERNAL_ERROR
}
